-- Auto-generated by seed-fragment-index.ts
-- Generated: 2026-02-27T22:26:12.666Z
-- Fragment count: 53

-- Clear existing data
DELETE FROM fragment_index;

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'continuous-monitoring',
  'capabilities',
  'Continuous Security Monitoring',
  '継続的セキュリティ監視',
  'capability-description',
  '2025-01',
  'production',
  '["security","monitoring","compliance"]',
  1,
  1,
  'fragments/capabilities/continuous-monitoring.en.md',
  'fragments/capabilities/continuous-monitoring.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'dns-email-reliability',
  'capabilities',
  'DNS & Email Reliability Monitoring',
  'DNS＆メール信頼性監視',
  'capability-description',
  '2025-01',
  'production',
  '["dns","email","monitoring","deliverability"]',
  1,
  1,
  'fragments/capabilities/dns-email-reliability.en.md',
  'fragments/capabilities/dns-email-reliability.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'infrastructure-management',
  'capabilities',
  'Managed IT Infrastructure',
  'マネージドITインフラストラクチャ',
  'capability-description',
  '2025-01',
  'production',
  '["infrastructure","management","cloud"]',
  1,
  1,
  'fragments/capabilities/infrastructure-management.en.md',
  'fragments/capabilities/infrastructure-management.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'modern-web-development',
  'capabilities',
  'Modern Web Development',
  'モダンWeb開発',
  'capability-description',
  '2025-01',
  'production',
  '["web","development","frontend"]',
  1,
  1,
  'fragments/capabilities/modern-web-development.en.md',
  'fragments/capabilities/modern-web-development.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'secure-hosting',
  'capabilities',
  'Enterprise-Grade Secure Hosting',
  'エンタープライズグレードのセキュアホスティング',
  'capability-description',
  '2025-01',
  'production',
  '["hosting","security","infrastructure"]',
  1,
  1,
  'fragments/capabilities/secure-hosting.en.md',
  'fragments/capabilities/secure-hosting.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'call-to-action',
  'closing',
  'Ready to Start',
  '始める準備',
  'closing',
  '2025-01',
  'production',
  '["all-clients","closing","cta","engagement"]',
  1,
  1,
  'fragments/closing/call-to-action.en.md',
  'fragments/closing/call-to-action.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'next-steps',
  'closing',
  'Next Steps',
  '次のステップ',
  'closing',
  '2025-01',
  'production',
  '["all-clients","closing","next-steps","workflow","onboarding"]',
  1,
  1,
  'fragments/closing/next-steps.en.md',
  'fragments/closing/next-steps.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'standard-closing',
  'closing',
  'In Closing',
  '最後に',
  'closing',
  '2025-01',
  'production',
  '["all-clients","closing","thank-you"]',
  1,
  1,
  'fragments/closing/standard-closing.en.md',
  'fragments/closing/standard-closing.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-12',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-contact',
  'company',
  'Contact Information',
  'お問い合わせ',
  'company-info',
  '2025-01',
  'production',
  '["company","contact","esolia"]',
  1,
  1,
  'fragments/company/esolia-contact.en.md',
  'fragments/company/esolia-contact.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-12',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-overview',
  'company',
  'About eSolia',
  'イソリアについて',
  'company-info',
  '2025-01',
  'production',
  '["company","about","esolia","overview","b2b","it-partner"]',
  1,
  1,
  'fragments/company/esolia-overview.en.md',
  'fragments/company/esolia-overview.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-12',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-comparison',
  'comparisons',
  'Password Vault Solutions: A Comparison Guide',
  'パスワード管理ソリューション比較ガイド',
  'comparison',
  '2026-01',
  'production',
  '["security","password-manager","1password","bitwarden","codebook","authentication","enterprise"]',
  1,
  1,
  'fragments/comparisons/password-vault-comparison.en.md',
  'fragments/comparisons/password-vault-comparison.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-01-26',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'cloudflare-security-layers',
  'diagrams',
  'Cloudflare Security Architecture',
  'Cloudflare セキュリティアーキテクチャ',
  'diagram',
  '2025-01',
  'production',
  '["cloudflare","security","architecture","zero-trust","network"]',
  1,
  1,
  'fragments/diagrams/cloudflare-security-layers.en.md',
  'fragments/diagrams/cloudflare-security-layers.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'cloudflare-three-layers',
  'diagrams',
  'Three Layers of Cloudflare Protection',
  'Cloudflare 3層の保護',
  'diagram',
  '2025-01',
  'production',
  '["cloudflare","security","dns","waf","zero-trust"]',
  1,
  1,
  'fragments/diagrams/cloudflare-three-layers.en.md',
  'fragments/diagrams/cloudflare-three-layers.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-cloudflare-m365-smb-security-coverage',
  'diagrams',
  'eSolia Cloudflare M365 SMB Security Coverage',
  'eSolia Cloudflare M365 SMB Security Coverage',
  'diagram',
  '2026-01',
  'production',
  '["diagram"]',
  1,
  1,
  'fragments/diagrams/esolia-cloudflare-m365-smb-security-coverage.en.md',
  'fragments/diagrams/esolia-cloudflare-m365-smb-security-coverage.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-01-09',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-m365-components',
  'diagrams',
  'eSolia M365 Components',
  'eSolia M365 Components',
  'diagram',
  '2026-01',
  'production',
  '["diagram"]',
  1,
  1,
  'fragments/diagrams/esolia-m365-components.en.md',
  'fragments/diagrams/esolia-m365-components.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-01-09',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'fiber-path-diagram-1',
  'diagrams',
  'Fiber Path Diagram 1',
  'Fiber Path Diagram 1',
  'diagram',
  '2026-01',
  'production',
  '["diagram"]',
  1,
  1,
  'fragments/diagrams/fiber-path-diagram-1.en.md',
  'fragments/diagrams/fiber-path-diagram-1.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-01-09',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'fortinet-small-office-network-diagram',
  'diagrams',
  'Fortinet Small Office Network Diagram',
  'Fortinet 小規模オフィスネットワーク図',
  'diagram',
  '2025-01',
  'production',
  '["fortinet","network","small-office","diagram"]',
  1,
  1,
  'fragments/diagrams/fortinet-small-office-network-diagram.en.md',
  'fragments/diagrams/fortinet-small-office-network-diagram.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-02-20',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-architecture-comparison-ja',
  'diagrams',
  'Security-First vs Convenience-First Architecture',
  'セキュリティ優先 vs 利便性優先アーキテクチャ',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","architecture"]',
  1,
  1,
  'fragments/diagrams/password-vault-architecture-comparison-ja.en.md',
  'fragments/diagrams/password-vault-architecture-comparison-ja.ja.md',
  'normal',
  'eSolia Technical Team',
  '2026-01-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-architecture-comparison',
  'diagrams',
  'Security-First vs Convenience-First Architecture',
  'Security-First vs Convenience-First Architecture',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","diagram"]',
  1,
  1,
  'fragments/diagrams/password-vault-architecture-comparison.en.md',
  'fragments/diagrams/password-vault-architecture-comparison.ja.md',
  'normal',
  'eSolia Technical Team',
  NULL,
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-attack-vectors-ja',
  'diagrams',
  'Security Architecture Comparison',
  'セキュリティアーキテクチャ比較',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","attack-vectors"]',
  1,
  1,
  'fragments/diagrams/password-vault-attack-vectors-ja.en.md',
  'fragments/diagrams/password-vault-attack-vectors-ja.ja.md',
  'normal',
  'eSolia Technical Team',
  '2026-01-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-attack-vectors',
  'diagrams',
  'Security Architecture Comparison',
  'Security Architecture Comparison',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","diagram"]',
  1,
  1,
  'fragments/diagrams/password-vault-attack-vectors.en.md',
  'fragments/diagrams/password-vault-attack-vectors.ja.md',
  'normal',
  'eSolia Technical Team',
  NULL,
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-cloud-sync-ja',
  'diagrams',
  'Cloud Sync Comparison',
  'クラウド同期の違い',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","cloud-sync","zero-knowledge"]',
  1,
  1,
  'fragments/diagrams/password-vault-cloud-sync-ja.en.md',
  'fragments/diagrams/password-vault-cloud-sync-ja.ja.md',
  'normal',
  'eSolia Technical Team',
  '2026-01-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-cloud-sync',
  'diagrams',
  'Cloud Sync Comparison',
  'Cloud Sync Comparison',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","diagram"]',
  1,
  1,
  'fragments/diagrams/password-vault-cloud-sync.en.md',
  'fragments/diagrams/password-vault-cloud-sync.ja.md',
  'normal',
  'eSolia Technical Team',
  NULL,
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-convenience-layer',
  'diagrams',
  'Convenience Layer Pattern',
  'Convenience Layer Pattern',
  'diagram',
  NULL,
  'production',
  '["password-manager","convenience-layer","best-practices"]',
  1,
  1,
  'fragments/diagrams/password-vault-convenience-layer.en.md',
  'fragments/diagrams/password-vault-convenience-layer.ja.md',
  'normal',
  'eSolia Technical Team',
  NULL,
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-decision-framework-ja',
  'diagrams',
  'Password Manager Decision Framework',
  'パスワードマネージャー意思決定フレームワーク',
  'diagram',
  NULL,
  'production',
  '["password-manager","decision-framework","comparison"]',
  1,
  1,
  'fragments/diagrams/password-vault-decision-framework-ja.en.md',
  'fragments/diagrams/password-vault-decision-framework-ja.ja.md',
  'normal',
  'eSolia Technical Team',
  '2026-01-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-decision-framework',
  'diagrams',
  'Password Manager Decision Framework',
  'Password Manager Decision Framework',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","diagram"]',
  1,
  1,
  'fragments/diagrams/password-vault-decision-framework.en.md',
  'fragments/diagrams/password-vault-decision-framework.ja.md',
  'normal',
  'eSolia Technical Team',
  NULL,
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-master-password-ja',
  'diagrams',
  'Master Password Concept',
  'マスターパスワードの概念',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","master-password"]',
  1,
  1,
  'fragments/diagrams/password-vault-master-password-ja.en.md',
  'fragments/diagrams/password-vault-master-password-ja.ja.md',
  'normal',
  'eSolia Technical Team',
  '2026-01-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-vault-master-password',
  'diagrams',
  'Master Password Concept',
  'Master Password Concept',
  'diagram',
  NULL,
  'production',
  '["password-manager","security","diagram"]',
  1,
  1,
  'fragments/diagrams/password-vault-master-password.en.md',
  'fragments/diagrams/password-vault-master-password.ja.md',
  'normal',
  'eSolia Technical Team',
  NULL,
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'pool-depletion-diagram',
  'diagrams',
  'Pool Depletion Over Time',
  'プール残高の推移',
  'diagram',
  '2025-01',
  'production',
  '["pool","support","hours","diagram"]',
  1,
  1,
  'fragments/diagrams/pool-depletion-diagram.en.md',
  'fragments/diagrams/pool-depletion-diagram.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-02-20',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'cloudflare-security-platform',
  'products',
  'Cloudflare Security Platform',
  'Cloudflare セキュリティプラットフォーム',
  'product-overview',
  '2025-01',
  'production',
  '["cloudflare","zero-trust","security","dns","warp","waf"]',
  1,
  1,
  'fragments/products/cloudflare-security-platform.en.md',
  'fragments/products/cloudflare-security-platform.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'fortinet-small-office-network',
  'products',
  'Fortinet Small Office Network',
  'Fortinet 小規模オフィスネットワーク',
  'product-overview',
  '2025-01',
  'production',
  '["fortinet","fortiwifi","fortiswitch","network","small-office","structured-cabling"]',
  1,
  1,
  'fragments/products/fortinet-small-office-network.en.md',
  'fragments/products/fortinet-small-office-network.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-02-20',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'm365-business-premium',
  'products',
  'Microsoft 365 Business Premium',
  'Microsoft 365 Business Premium',
  'product-overview',
  '2025-01',
  'production',
  '["m365","licensing","productivity","security","defender","intune"]',
  1,
  1,
  'fragments/products/m365-business-premium.en.md',
  'fragments/products/m365-business-premium.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-agreement-characteristics',
  'proposals',
  'Agreement Structure',
  'ご契約について',
  'proposal-section',
  '2025-12',
  'production',
  '["initial-client","proposal","agreement","billing","terms"]',
  1,
  1,
  'fragments/proposals/esolia-agreement-characteristics.en.md',
  'fragments/proposals/esolia-agreement-characteristics.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-background',
  'proposals',
  'eSolia Background',
  'イソリア バックグラウンド',
  'proposal-section',
  '2025-12',
  'production',
  '["initial-client","proposal","background","approach"]',
  1,
  1,
  'fragments/proposals/esolia-background.en.md',
  'fragments/proposals/esolia-background.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-closing',
  'proposals',
  'In Closing',
  '最後に',
  'proposal-section',
  '2025-01',
  'production',
  '["proposal","closing","next-steps","all-clients"]',
  1,
  1,
  'fragments/proposals/esolia-closing.en.md',
  'fragments/proposals/esolia-closing.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-12',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-introduction',
  'proposals',
  'eSolia Introduction',
  'イソリア紹介',
  'proposal-section',
  '2025-12',
  'production',
  '["initial-client","proposal","introduction","B2B"]',
  1,
  1,
  'fragments/proposals/esolia-introduction.en.md',
  'fragments/proposals/esolia-introduction.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-profile',
  'proposals',
  'eSolia Profile',
  'イソリア プロフィール',
  'proposal-section',
  '2025-12',
  'production',
  '["initial-client","proposal","profile","company-info"]',
  1,
  1,
  'fragments/proposals/esolia-profile.en.md',
  'fragments/proposals/esolia-profile.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-project-types',
  'proposals',
  'eSolia Project Types',
  'プロジェクト実績',
  'proposal-section',
  '2025-12',
  'production',
  '["initial-client","proposal","projects","experience"]',
  1,
  1,
  'fragments/proposals/esolia-project-types.en.md',
  'fragments/proposals/esolia-project-types.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-service-mechanics',
  'proposals',
  'Service Mechanics',
  'サービスの仕組み',
  'proposal-section',
  '2025-12',
  'production',
  '["all-clients","proposal","service","support"]',
  1,
  1,
  'fragments/proposals/esolia-service-mechanics.en.md',
  'fragments/proposals/esolia-service-mechanics.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-support-types',
  'proposals',
  'Support Types',
  'サポートの種類',
  'proposal-section',
  '2025-12',
  'production',
  '["all-clients","proposal","support","totalsupport","co-support"]',
  1,
  1,
  'fragments/proposals/esolia-support-types.en.md',
  'fragments/proposals/esolia-support-types.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'cosupport',
  'services',
  'Co-Support — Collaborative IT Partnership',
  'Co-Support — コラボレーティブITパートナーシップ',
  'service-description',
  '2025-01',
  'production',
  '["support","co-support","augmentation","partnership"]',
  1,
  1,
  'fragments/services/cosupport.en.md',
  'fragments/services/cosupport.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-02-20',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'esolia-after-hours-support',
  'services',
  'After Hours Support',
  '営業時間外サポート',
  'service-info',
  '2025-01',
  'production',
  '["repeat-client","support","after-hours","existing-clients","emergency"]',
  1,
  1,
  'fragments/services/esolia-after-hours-support.en.md',
  'fragments/services/esolia-after-hours-support.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-12',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'm365-security-essentials-pricing',
  'services',
  'M365 Security Essentials - Timeline & Pricing',
  'M365 セキュリティ・エッセンシャルズ - スケジュール・料金',
  'pricing-table',
  '2025-01-v4',
  'production',
  '["m365","security","cloudflare","pricing","timeline","smb"]',
  1,
  1,
  'fragments/services/m365-security-essentials-pricing.en.md',
  'fragments/services/m365-security-essentials-pricing.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-15',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'm365-security-essentials',
  'services',
  'M365 Security Essentials',
  'M365 セキュリティ・エッセンシャルズ',
  'service-description',
  '2025-01',
  'production',
  '["m365","security","cloudflare","zero-trust","smb","email-security","dmarc"]',
  1,
  1,
  'fragments/services/m365-security-essentials.en.md',
  'fragments/services/m365-security-essentials.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-15',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'ongoing-support',
  'services',
  'Ongoing IT Support Services',
  '継続的ITサポートサービス',
  'service-description',
  '2025-01',
  'production',
  '["support","helpdesk","managed-services"]',
  1,
  1,
  'fragments/services/ongoing-support.en.md',
  'fragments/services/ongoing-support.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'password-manager',
  'services',
  'Password Manager Recommendation',
  'パスワードマネージャー推奨',
  'service-description',
  '2025-01',
  'production',
  '["security","password","authentication","1password","bitwarden"]',
  1,
  1,
  'fragments/services/password-manager.en.md',
  'fragments/services/password-manager.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'periodic-monitoring',
  'services',
  'DNS & Email Monitoring (Periodic)',
  'DNS・メール監視（Periodic）',
  'service-description',
  '2025-01',
  'production',
  '["dns","email","monitoring","spf","dkim","dmarc","periodic"]',
  1,
  1,
  'fragments/services/periodic-monitoring.en.md',
  'fragments/services/periodic-monitoring.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-12-27',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'pool-mechanics',
  'services',
  'Pool — Pre-Purchased Support Hours',
  'プール — 事前購入サポート時間',
  'service-description',
  '2025-01',
  'production',
  '["pool","support","hours","flexible"]',
  1,
  1,
  'fragments/services/pool-mechanics.en.md',
  'fragments/services/pool-mechanics.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-02-20',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'totalsupport',
  'services',
  'TotalSupport — Comprehensive Managed IT',
  'TotalSupport — 包括的マネージドIT',
  'service-description',
  '2025-01',
  'production',
  '["support","managed-services","totalsupport","outsourcing"]',
  1,
  1,
  'fragments/services/totalsupport.en.md',
  'fragments/services/totalsupport.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2026-02-20',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'website-development',
  'services',
  'Website Development Services',
  'ウェブサイト開発サービス',
  'service-description',
  '2025-01',
  'production',
  '["website","development","project"]',
  1,
  1,
  'fragments/services/website-development.en.md',
  'fragments/services/website-development.ja.md',
  'normal',
  'rick.cogley@esolia.co.jp',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'billing-terms',
  'terms',
  'Billing Model',
  '請求モデル',
  'terms-conditions',
  '2025-01',
  'production',
  '["terms","billing","pricing","rates"]',
  1,
  1,
  'fragments/terms/billing-terms.en.md',
  'fragments/terms/billing-terms.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'confidentiality',
  'terms',
  'Confidentiality & Data Protection',
  '機密保持とデータ保護',
  'terms-conditions',
  '2025-01',
  'production',
  '["terms","confidentiality","nda","privacy","security"]',
  1,
  1,
  'fragments/terms/confidentiality.en.md',
  'fragments/terms/confidentiality.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-08',
  '2026-02-27 22:26:12'
);

INSERT INTO fragment_index (id, category, title_en, title_ja, type, version, status, tags, has_en, has_ja, r2_key_en, r2_key_ja, sensitivity, author, created_at, updated_at) VALUES (
  'standard-terms',
  'terms',
  'Agreement Structure',
  'ご契約について',
  'terms-conditions',
  '2025-01',
  'production',
  '["terms","agreement","msa","sow","contract"]',
  1,
  1,
  'fragments/terms/standard-terms.en.md',
  'fragments/terms/standard-terms.ja.md',
  'normal',
  'eSolia Technical Team',
  '2025-01-08',
  '2026-02-27 22:26:12'
);
